### ISSUE TITLE
[BUG] stack overflow with zero-width stroke

### ISSUE THREAD

**Issue by CinusMinus** [38/plotters#267]
**Describe the bug**
Attempting to draw a zero-width line will cause a stack overflow with plotters 0.3.1. Expected behaviour: Nothing is drawn. Maybe something very thin. But no stack overflow.

**To Reproduce**
`main.src`
```rust
use plotters::prelude::*;

fn main() {
    let p1 = (338, 122);
    let p2 = (365, 122);

    let mut backend = BitMapBackend::new("blub.png", (800, 600));

    backend.draw_line(p1, p2, &RGBColor(0, 0, 0).stroke_width(0)).unwrap();
}
```
`Cargo.toml`
```toml
[package]
name = "plottest"
version = "0.1.0"
edition = "2018"

[dependencies]
plotters = "0.3.1"
```
Result:
```
> cargo run
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
[1]    123 abort (core dumped)  cargo run
```
If I change the line width to 1 it works.

**Version Information**
plotters 0.3.1
